apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  DB_HOST: "postgresql-service.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "mydatabase"
  DB_USER: "myuser"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==